In [1]:
import os

from keras.preprocessing import image
from keras.applications.vgg19 import VGG19
from keras.applications.vgg19 import preprocess_input
import numpy as np
from keras.layers import merge, Input

image_input = Input(shape=(224,224,3))

model = VGG19(include_top=False,weights="imagenet",input_tensor=image_input)

#model.summary()



Using TensorFlow backend.
/Users/siqi/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,


In [2]:
# from PIL import Image
# data_dir = os.listdir("./data")
# #img = Image.open('./data/1.png').convert('LA')
# #img.save("./data/233.png")

# for i in data_dir:
#   if not i.endswith(".png"):
#     continue
#   img_path ="./data/"+i
#   img = Image.open(img_path).convert('LA')
#   img.save("./data_gray/"+i)


In [3]:
data_dir = os.listdir("./data")
data_dir.sort()
print data_dir


vgg19_feature_list=[]
data_dir_new = []
for i in data_dir:
  if not i.endswith(".png"):
    continue
  data_dir_new.append(i)
  img_path ="./data/"+i
  img = image.load_img(img_path, target_size=(224, 224))
  img_data = image.img_to_array(img)
  img_data = np.expand_dims(img_data, axis=0)
  img_data = preprocess_input(img_data)

  vgg19_feature = model.predict(img_data)
  vgg19_feature_np = np.array(vgg19_feature,dtype="float64")
  vgg19_feature_list.append(vgg19_feature_np.flatten())
data_dir = data_dir_new

vgg19_feature_list_np = np.array(vgg19_feature_list)

vgg19_feature_list_np.shape

print vgg19_feature_list_np


['.DS_Store', '0001.png', '0002.png', '0003.png', '0004.png', '0005.png', '0006.png', '0007.png', '0008.png', '0009.png', '0010.png', '0011.png', '0012.png', '0013.png', '0014.png', '0015.png', '0016.png', '0017.png', '0018.png', '0019.png', '0020.png', 'list.txt']
[[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]


In [4]:
import math
def euclidean_distance(vector1, vector2):
    '''calculate the euclidean distance, no numpy
    input: numpy.arrays or lists
    return: euclidean distance
    '''
    dist = [(a - b)**2 for a, b in zip(vector1, vector2)]
    dist = math.sqrt(sum(dist))
    return dist
def KNN(feature, feature_list,K):
    distances = []
    for i,ft in enumerate(feature_list):
        #print feature, ft, ft - feature
        #distance = euclidean_distance(feature, ft)
        distance = np.linalg.norm(ft - feature)
        distances.append([distance,i,data_dir[i]])
    distances.sort()
    return distances[:K]


In [5]:
for i,feature in enumerate(vgg19_feature_list_np):
    #distances = KNN(feature, vgg19_feature_list_np, len(vgg19_feature_list_np))
    distances = KNN(feature, vgg19_feature_list_np, 2)
    print i, data_dir[i], distances

0 0001.png [[0.0, 0, '0001.png'], [1094.3219332507679, 1, '0002.png']]
1 0002.png [[0.0, 1, '0002.png'], [1094.3219332507679, 0, '0001.png']]
2 0003.png [[0.0, 2, '0003.png'], [1131.172848581218, 3, '0004.png']]
3 0004.png [[0.0, 3, '0004.png'], [1131.172848581218, 2, '0003.png']]
4 0005.png [[0.0, 4, '0005.png'], [1606.1201433751642, 3, '0004.png']]
5 0006.png [[0.0, 5, '0006.png'], [1652.751558235913, 3, '0004.png']]
6 0007.png [[0.0, 6, '0007.png'], [1125.8397613937736, 9, '0010.png']]
7 0008.png [[0.0, 7, '0008.png'], [1100.4581914190398, 9, '0010.png']]
8 0009.png [[0.0, 8, '0009.png'], [1383.729952824307, 9, '0010.png']]
9 0010.png [[0.0, 9, '0010.png'], [1100.4581914190398, 7, '0008.png']]
10 0011.png [[0.0, 10, '0011.png'], [1673.4291947875968, 9, '0010.png']]
11 0012.png [[0.0, 11, '0012.png'], [1432.4866201072073, 9, '0010.png']]
12 0013.png [[0.0, 12, '0013.png'], [1154.5149669820726, 13, '0014.png']]
13 0014.png [[0.0, 13, '0014.png'], [1103.2414873545606, 14, '0015.png']]
